### ISSUE TITLE
Dev builds drop the services that were configured in latest 0.10.1 release

### ISSUE THREAD

**Issue by gnu010** [LibreRambox/LibreRambox#20] opened 2024-03-19 20:20 UTC
### Steps to reproduce

1. Install latest 0.10.1 release. https://github.com/LibreRambox/LibreRambox/releases/tag/v0.10.1
2. Start LibreRambox and configure at least one service. Its folder can be seen in `~/.config/LibreRambox/Partitions`
3. Close LibreRambox completely.
4. Upgrade to a dev build, e.g. f676fc3 from PR #18. (`LibreRambox-linux-amd64.deb` from https://github.com/LibreRambox/LibreRambox/actions/runs/8309866257)
5. Start LibreRambox.

### Expected behavior

The previously configured service(s) is/are still up and running.

### Actual behavior

The previously configured service(s) is/are missing.

Nevertheless, when adding the missing service again, it immediately appears in its last state (i.e. logged in).

### ENVIRONMENT

> LibreRambox: v0.10.1 versus dev build f676fc3

> OS: Linux Mint 21.3 Virginia

> Arch: x64

**Comment by KevinRoebert** [comment] 2024-03-20 12:24
Yes, the problem is well known. Unfortunately, my [MR](https://github.com/LibreRambox/LibreRambox/pull/14) was merged into the master before it was finished. By changing the namespace, the sessions for all the services are now located somewhere else. I still have to find out how I can migrate the sessions to the new namespace.

**Comment by KevinRoebert** [comment] 2024-03-20 12:35
I've removed the commit from master and opened a new draf MR: #21

**Comment by gnu010** [comment] 2024-03-20 18:38
Confirmed, this now works.

**Closed** 2024-05-06 08:09 UTC
Labels: bug
